### ISSUE TITLE
Ignore towncrier setup

### ISSUE THREAD

**Issue by petschki** [plone/meta#154]
I'm starting to use `plone/meta` on my collective packages but there I do not want towncrier setup at all. Would this be a feature for `.meta.toml` like

```
[pyproject]
towncrier_skip = true
```

or is it mandatory to use towncrier if we configure with meta?

**Comment by gforcada** [comment]
The idea of `plone/meta` is first to serve as a common ground for plone core packages, but it will be much more useful if collective, and specially also, private repositories also use it. This way any fix/improvement that you want for plone core, collective or private packages benefits everyone.

Skipping towncrier might be a bit borderline of if it's a good idea or not to configure it, as in general, you always end up in conflicts in `CHANGES` files. With only 2 pull requests at the same time you already have such conflicts 😓 

Nonetheless, we can make it configurable, _but without an option_: i.e. if the `news` folder is found, we add a `towncrier` configuration on `pyproject.toml`, otherwise we print a message warning about it and continue.

One question: usually `plone/meta` adds a news entry snippet to mention that it has been configured, should we do nothing for your use case? That would be the easiest 🍀 

If you like this approach I can either do it, or I would be glad to review it as soon as it is ready.

Note that you can keep configuring your repositories before the changes get merged, so you don't get blocked.

Let us know which other shortcomings you find! 🤩

**Comment by petschki** [comment]
Thanks for clarifying.

Here some experiences on my brand new MacBook:

Following the `config/README` I've installed python 3.11.3 and did a `pip install -rrequirements.txt` there.
When trying to run `config-package.py` I get this traceback (strange ... I didn't get this on my office Mac when I installed and run meta there a some time ago):

```
Traceback (most recent call last):
  File "/Users/peterm/workspace/meta/config/config-package.py", line 9, in <module>
    from shared.toml_encoder import TomlArraySeparatorEncoderWithNewline
  File "/Users/peterm/workspace/meta/config/shared/toml_encoder.py", line 1, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
```

So I added `toml` to the `requirements.txt`, pip installed again and this was gone.
But there was a new traceback:

```
collective.gridlisting is already configured for this config type, updating.
Traceback (most recent call last):
  File "/Users/peterm/workspace/meta/config/config-package.py", line 503, in <module>
    main()
  File "/Users/peterm/workspace/meta/config/config-package.py", line 500, in main
    package.configure()
  File "/Users/peterm/workspace/meta/config/config-package.py", line 476, in configure
    files = method()
            ^^^^^^^^
  File "/Users/peterm/workspace/meta/config/config-package.py", line 277, in pyproject_toml
    shutil.copy(
  File "/Users/peterm/.pyenv/versions/3.11.3/lib/python3.11/shutil.py", line 419, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/peterm/.pyenv/versions/3.11.3/lib/python3.11/shutil.py", line 258, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/peterm/workspace/meta/config/../../interreg/src/collective.gridlisting/news/.changelog_template.jinja'
```

Turns out, that my package had a `CHANGES.md` file but **no** `news/` folder ... now the script wants to copy towncrier template immediately but can't. Changed my suffix of CHANGES to `rst` and now it can be configured... the news folder was generated automatically though...

I'll prepare a PR which fixes the two things above.

But to come back to the point: checking for existing `news` folder and give an info if it has to be created manually if you want to use towncrier would be my preferred solution 👍🏼
