### ISSUE TITLE
Remove the master branch

### ISSUE THREAD

**Issue by thet** [plone/meta#199]
This repo has a `master` and a `main` branch. `main` is the default one.

Please remove the "master" branch. It is confusing and one can easily do a `git checkout master` without a warning and not recognizing that the `main` branch is the default one.

**Comment by ale-rt** [comment]
I just removed it, it was 97 commits behind and had no commit more than master

**Comment by gforcada** [comment]
I was keeping it as at the beginning there were a few globlal CI jobs that were pointing to the master branch specifically.

Hopefully everyone will have updated them since then 🤞🏾 otherwise, they will complain 😄

**Comment by mauritsvanrees** [comment]
I have created https://github.com/plone/plone.folder/pull/26 and there the [GitHub Actions say](https://github.com/plone/plone.folder/actions/runs/7590657273):

[Invalid workflow file: .github/workflows/meta.yml#L20](https://github.com/plone/plone.folder/actions/runs/7590657273/workflow)
error parsing called workflow
".github/workflows/meta.yml"
-> "plone/meta/.github/workflows/test.yml@master"
: failed to fetch workflow: reference to workflow should be either a valid branch, tag, or commit


So `plone.folder` still tries to use the master branch, which fails.  Result is that the actions fail in such a way that you do not even see them in the checks of the PR: the checks only show the pre-commit CI check, Plone Contributors Agreement verifier, the Changelog verifier, and Jenkins.

So the danger now that the master branch is gone, is that people will fail to notice that something is wrong.  But until now these repos would use a long outdated branch, so that was bad too.

Conclusion: it was good to remove the master branch, but we should pay attention the coming weeks/months when there is a PR and no plone/meta checks are reported.

**Comment by gforcada** [comment]
Time to run a full scale search and replace across repositories then 🧹 😄

**Comment by gforcada** [comment]
_Maybe with outdated checkouts..._

That's all the repositories that still point to the `master` branch.

```shell
$ /bin/grep plone/meta/.github/workflows/ */.github/workflows/meta.yml | /bin/grep -v 'main' | cut -d":" -f1 | sort | uniq 
plone.alterego/.github/workflows/meta.yml
plone.app.contentmenu/.github/workflows/meta.yml
plone.app.contenttypes/.github/workflows/meta.yml
plone.app.dexterity/.github/workflows/meta.yml
plone.app.event/.github/workflows/meta.yml
plone.app.i18n/.github/workflows/meta.yml
plone.app.intid/.github/workflows/meta.yml
plone.app.linkintegrity/.github/workflows/meta.yml
plone.app.portlets/.github/workflows/meta.yml
plone.app.querystring/.github/workflows/meta.yml
plone.app.redirector/.github/workflows/meta.yml
plone.app.relationfield/.github/workflows/meta.yml
plone.app.textfield/.github/workflows/meta.yml
plone.app.uuid/.github/workflows/meta.yml
plone.app.versioningbehavior/.github/workflows/meta.yml
plone.autoform/.github/workflows/meta.yml
plone.base/.github/workflows/meta.yml
plone.behavior/.github/workflows/meta.yml
plone.dexterity/.github/workflows/meta.yml
plone.distribution/.github/workflows/meta.yml
plone.folder/.github/workflows/meta.yml
plone.formwidget.recurrence/.github/workflows/meta.yml
plone.indexer/.github/workflows/meta.yml
plone.keyring/.github/workflows/meta.yml
plone.locking/.github/workflows/meta.yml
plone.memoize/.github/workflows/meta.yml
plone.outputfilters/.github/workflows/meta.yml
plone.portlet.collection/.github/workflows/meta.yml
plone.portlet.static/.github/workflows/meta.yml
plone.protect/.github/workflows/meta.yml
plone.registry/.github/workflows/meta.yml
plone.resource/.github/workflows/meta.yml
plone.rfc822/.github/workflows/meta.yml
plone.session/.github/workflows/meta.yml
plone.stringinterp/.github/workflows/meta.yml
plone.supermodel/.github/workflows/meta.yml
plone.transformchain/.github/workflows/meta.yml
plone.uuid/.github/workflows/meta.yml
Products.isurlinportal/.github/workflows/meta.yml
```

**Comment by ale-rt** [comment]
Sorry for the unintended consequences of my reckless act :)
At least, now we have updated actions on the packages...

Sorry again and thanks!
