### ISSUE TITLE
Move check-manifest config to pyproject.toml?

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/meta#56]
From [comment by @jensens](https://github.com/plone/plone.i18n/pull/50#discussion_r1129317058).

I don't have a big preference.  But `setup.cfg` kind of belongs to `setuptools`, so we may want to move away from that.

**Comment by gforcada** [comment]
I'm all happy to ditch `setup.cfg` and move things to `pyproject.toml`, I was having a look at:

```ini
[bdist_wheel]
universal = 0
```

And turns out that if you build a distribution with python 3 that's already the default, i.e. we can remove these two lines from `setup.cfg` 🎉 

We can move `check-manifest` to `pyproject.toml` and then only `flake8` configuration would be left in `setup.cfg`.

I know that @ericof wants to use [FlakeHeaven](https://flakeheaven.readthedocs.io/en/latest/index.html) that has `pyproject.toml` support 😉 I'm not a fan of wrappers though 🤷🏾 

We could move its configuration to a `.flake8` file where then it would be even more easy to keep control on the file and not have the problems that `pyproject.toml` will have if we eventually move `setup.py` partially/completely to it 😖

**Comment by ericof** [comment]
Let's do this then. Move flake8 config to .flake8, and everything else to project.toml.

**Comment by mauritsvanrees** [comment]
Note that `zest.releaser` 7 and earlier look at the existence of a `bdist_wheel` section to decide if it will create a wheel or not.  The value of `universal` does not matter.  But starting from `zest.releaser` 8, creating a wheel is the default, even without this section.  So should be fine to remove it.
