### ISSUE TITLE
Linter: more flake8 plugins

### ISSUE THREAD

**Issue by gforcada** [plone/meta#71]
In the old `plone.recipe.codeanalysis` tool that we built long ago, we had quite a few plugins enabled,

```
flake8-blind-except
flake8-builtins
flake8-debugger
flake8-deprecated
flake8-pep3101
flake8-plone-hasattr
flake8-print
flake8-todo
```

At some point we can enable them once more in pre-commit 🤔 maybe revisit which ones we actually want to enable... like `dlint` #70 for example

**Comment by mauritsvanrees** [comment]
A problem I frequently had when `plone.recipe.codeanalysis` was used in add-ons, was that I spent 5 minutes on a bugfix, and then an hour getting the CI to pass again because of a version conflict, especially when testing across multiple Plone and Python versions, and especially when the add-on was not getting a lot of attention.

In core Plone the situation will be different, but still: the more packages we add for doing checks, the more time we will need to spend on keeping a list of compatible versions.  We need to balance that against the improved code that each package brings.
It should be a bit less problematic though, now that all such tools will work on Python 3.

**Comment by gforcada** [comment]
Yup, that's I was a bit wary of `pre-commit`, as I was fearing that having to keep an extra set of version pins would make things _unstable_.

But, @ale-rt correct me if I'm wrong, I think that `pre-commit` allows to specify dependencies for each check and at the same time pin those versions, right? Otherwise an externally-centralized way to manage `pre-commit` versions would be needed, which I think is also possible, as one of my ex-colleagues configured `pre-commit` somehow this way 🤔

**Comment by ale-rt** [comment]
> But, @ale-rt correct me if I'm wrong, I think that pre-commit allows to specify dependencies for each check and at the same time pin those versions, right?

Yes, it is possible, see for example: https://github.com/collective/zpretty/blob/10a560fc787cff40ded0a99e0dc628145cfc95b5/.pre-commit-config.yaml#L10-L16
Every check is in its own virtualenv, so no fear that it will clash with buildout or something else
