### ISSUE TITLE
Be careful with overriding stuff in setup.cfg

### ISSUE THREAD

**Issue by jensens** [plone/meta#82]
specific case: in flake8 sections, the 
```
per-file-ignores =
    src/plone/base/interfaces/__init__.py:F401
    src/plone/base/permissions.py:F401,E402
```
got removed.

Overall: Only sections and values to be changed should be touched.

**Comment by gforcada** [comment]
🙋🏾 that was me being lazy 😅 

One needs to add an option so we can add these configuration lines in `.meta.cfg` so whenever `setup.cfg` gets recreated they can be restored.

That's already possible with a few other options but not for everything, my first idea was to get _almost_ all packages with GHA enabled to ensure tests do run on each repository and then clean up and improve.

What might not be too nice/easy is for repositories that heavily use `pyproject.toml` (like as a replacement for all `setup.py` metadata).

We might think of another strategy there 🤔

**Comment by mauritsvanrees** [comment]
We could have a marker comment line, where plone/meta keeps whatever lines are below it. Or above, whatever is handier.

But this works best when you manually want to add an entire section, not when you want to add an option to one or more sections.

**Comment by jensens** [comment]
I would add a marker to start a meta block and to end it, thus things get explicit.

```
bla bla, this got never touched.

# begin plone/meta

whatever is here get overriden

# end plone/meta

foo bar, this is stable

**Comment by gforcada** [comment]
But on setup.cfg we don't have only `flake8` configuration that might get overridden, we also have `coverage` options, `zest.releaser` configuration, `check-manifest` ...

That's why https://github.com/zopefoundation/meta have that many configuration options to keep the data on `.meta.toml` to re-create the other configuration files together with the templates from `meta` repository.

I don't think it makes sense to reinvent the wheel if they have already done so 😅

**Comment by mauritsvanrees** [comment]
What I sometimes find frustrating, is that a `pyproject.toml` is generated, I notice that for example an extra dependencychecker mapping is needed, I know how to write this, but instead of simply adding it, I have to lookup in the readme what the `plone/meta` spelling of this option is.

How about merging items from `.meta.toml` into `pyproject.toml`?  
So instead of this plone/meta-specific config:

```
[dependencies]
mappings = [
    "foo = ['bar', 'baz']",
    ]
```

you would have this standard config:

```
[tool.dependencychecker]
foo = ['bar', 'baz']
```

What would then happen:

- We rename `pyproject.toml.j2` to e.g.  `pyproject-base.toml`, and remove the logic (conditions, loops).
- `plone/meta` parses `pyproject-base.toml`.
- `plone/meta` parses `.meta.toml`.
- `plone/meta` combines the two and lets `toml` write it out.

Not sure if combining and writing works nicely.

Alternatively, just read `.meta.toml` and use it in the same way as we do now: we parse a `dependencies_mapping` from it and insert that into `pyproject.toml` in the current way.

Perhaps similarly have a `.meta.setup.cfg` and combine that into `setup.cfg`, so you don't have `[check-manifest] additional-ignores = [...]` but simply `[check-manifest] ignore = ...`

I think there are possibilities, but combining options for the same section is always going to be a bit tricky.

**Comment by jensens** [comment]
I like the idea. Using the current standard parsers I know all comments in the file would get lost, which is not that handy.

**Comment by gforcada** [comment]
I missed the previous comments, sorry 🙏🏾 

I see/feel the pain myself 😢 I see a few options:

1. make the option names simpler to discover (what @mauritsvanrees mentions to have to go around `plone/meta` to find the variable name), that's kind of the idea with #92 
1. self documenting options in the configuration files, like [1]
1. create a `meta` folder, where we store the file overrides on a per file basis, i.e. `meta/.flake8`, `meta/pyproject.toml`

The third option feels to be repeating the same problem as we are having now, but at a smaller scale, and specially merging, as @jensens points out, would mean losing comments, which is quite an important part of a configuration file.

The more I think of the second option, the more I like it ✨ it allows us to keep the same functionality as we have it now, plus it makes things explicit and educates whoever stumbles upon a configuration file and wants to tweak a setting or two there.

[1] Example `.flake8` (an ini file):

```ini
[flake8]
ignore = 
    # comment
    E456
# to insert more options set on .meta.toml the option
# [flake8]
# extra_lines = """
# MY CHANGES
# """
```

This way the files are self explanatory, as well as the injection points from within each project, rather than being some obscure decision made in an external repository.

The point of view is almost always from the repository that you applied `plone/meta` on, rather than from `plone/meta` that you want to add extra functionality.
